### ISSUE TITLE
Xbox controller not working and crashing

### ISSUE THREAD

**Issue by ThePajus** [wefcdse/fpv20#2]
Even though I can calibrate the controller, I cant move or do anything and when I try to check the inputs or change control buttons it crashes.
![image](https://github.com/wefcdse/fpv20/assets/66204238/205efde6-ffc6-474d-8dc1-d74aee8bf854)

**Comment by wefcdse** [comment]
very sorry about that, my controller had only 5 channels
try the new version, the .jar file can be found in github Actions.

**Comment by wefcdse** [comment]
> very sorry about that, my controller had only 5 channels try the new version, the .jar file can be found in github Actions.

or in curseforge, just uploaded it (it takes time to be approve, the version is 1.1.1

**Comment by wefcdse** [comment]
@ThePajus  can this mod run now? I don't have a Xbox controller so i cannot test it

**Comment by illegalPie** [comment]
Even though it doesn't crash anymore like it used to. It still doesn't work. When I move the sticks in flight mode nothing happens.

**Comment by wefcdse** [comment]
made a new fix, however still not have Xbox controller so please tell me if it works. if not, please send me a screen record

**Comment by illegalPie** [comment]
https://github.com/wefcdse/fpv20/assets/66204238/500d1a50-4861-4315-8eed-3de734ff2f61

**Comment by wefcdse** [comment]
set the sticks' channel name to:
throttle:
t
yaw:
y
pitch:
p
roll:
r
in calibration/option screen

**Comment by illegalPie** [comment]
I got it to work but my individual controls are inverted + I'm going faster than the speed of light.

**Comment by wefcdse** [comment]
try set

**Comment by wefcdse** [comment]
try set throttle's fix type to maxmin

**Comment by wefcdse** [comment]
i know what's wrong......
maybe i need a few days(1 ~ 7 ?) to fix it.

**Comment by illegalPie** [comment]
Hello, did you fix it?

**Comment by wefcdse** [comment]
> Hello, did you fix it?

try the new version , note that stick goes up and right should be positive signal. if not , set reversed in calibration/option screen.
also, if your controller's throttle stick goes back to center when you donot hold it, set throttle' fix type to maxmidmin
