### ISSUE TITLE
Addition of Rate Multipliers

### ISSUE THREAD

**Issue by JoelDankert** [wefcdse/fpv20#3]
with the current 2 rate values, add a third one that multiplies the endresult by a number. so you can effectively change the maxrate

**Comment by wefcdse** [comment]
ok, tomorrow,
i'll make it in config, is that ok?

**Comment by JoelDankert** [comment]
that would be so incredible. thank you so much!! have a nice day and much
fun programming

wefcdse ***@***.***> schrieb am Mo., 8. Apr. 2024, 14:39:

**Comment by wefcdse** [comment]
made a new config angular_velocity__deg_sec in config/fpv20_client.json :)

**Comment by JoelDankert** [comment]
Thanks, I tried it and its working fine

Am Di., 9. Apr. 2024 um 15:13 Uhr schrieb wefcdse ***@***.***
