### ISSUE TITLE
Xbox Controller problems with deadzones

### ISSUE THREAD

**Issue by dusieq95** [wefcdse/fpv20#6]
Well i have a problems with deadzones, they kinda doesn't work as you can see here: https://youtu.be/0ZjmPa76qks

**Comment by wefcdse** [comment]
i don't quite understand because i don't have a Xbox Controller.......but try the new version in github action though

**Comment by wefcdse** [comment]
did the new version work?

**Comment by wefcdse** [comment]
https://github.com/wefcdse/fpv20/actions/runs/10242867031
